import { RatioType } from './graphql.js';

export const origworld = {
  name: 'Clinique Saint-Espoir',
  logo: 'icones/hopital.jpg',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: 'Consultation',
      logo: 'icones/consultation.jpg',
      cout: 4,
      croissance: 1.07,
      revenu: 1,
      vitesse: 1000,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: "Salle d'attente agrandie",
          logo: 'icones/consultation.jpg',
          seuil: 20,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Assistant médical',
          logo: 'icones/consultation.jpg',
          seuil: 50,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Certification qualité',
          logo: 'icones/consultation.jpg',
          seuil: 150,
          idcible: 1,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Radiologie',
      logo: 'icones/radiologie.jpg',
      cout: 60,
      croissance: 1.15,
      revenu: 60,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Nouvelle salle de radio',
          logo: 'icones/radiologie.jpg',
          seuil: 20,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Technicien qualifié',
          logo: 'icones/radiologie.jpg',
          seuil: 50,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Service accrédité',
          logo: 'icones/radiologie.jpg',
          seuil: 150,
          idcible: 2,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 3,
      name: 'Bloc opératoire',
      logo: 'icones/bloc.jpg',
      cout: 720,
      croissance: 1.14,
      revenu: 540,
      vitesse: 6000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Salle stérile supplémentaire',
          logo: 'icones/bloc.jpg',
          seuil: 20,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Chirurgien senior',
          logo: 'icones/bloc.jpg',
          seuil: 50,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Réputation chirurgicale',
          logo: 'icones/bloc.jpg',
          seuil: 150,
          idcible: 3,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 4,
      name: 'Laboratoire',
      logo: 'icones/labo.jpg',
      cout: 8640,
      croissance: 1.13,
      revenu: 4320,
      vitesse: 12000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Nouveaux analyseurs',
          logo: 'icones/labo.jpg',
          seuil: 20,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Biologiste expert',
          logo: 'icones/labo.jpg',
          seuil: 50,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Laboratoire de référence',
          logo: 'icones/labo.jpg',
          seuil: 150,
          idcible: 4,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 5,
      name: 'Soins intensifs',
      logo: 'icones/reanimation.jpg',
      cout: 103680,
      croissance: 1.12,
      revenu: 51840,
      vitesse: 24000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Lits de réanimation supplémentaires',
          logo: 'icones/reanimation.jpg',
          seuil: 20,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Équipe de nuit renforcée',
          logo: 'icones/reanimation.jpg',
          seuil: 50,
          idcible: 5,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Unité de pointe',
          logo: 'icones/reanimation.jpg',
          seuil: 150,
          idcible: 5,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 6,
      name: 'Imagerie IRM',
      logo: 'icones/irm.jpg',
      cout: 1244160,
      croissance: 1.11,
      revenu: 622080,
      vitesse: 96000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Deuxième appareil IRM',
          logo: 'icones/irm.jpg',
          seuil: 20,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Radiologue spécialisé',
          logo: 'icones/irm.jpg',
          seuil: 50,
          idcible: 6,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
        {
          name: 'Centre de référence régional',
          logo: 'icones/irm.jpg',
          seuil: 150,
          idcible: 6,
          ratio: 3,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
  ],
  allunlocks: [
    {
      name: 'Accréditation régionale',
      logo: 'icones/all.jpg',
      seuil: 25,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Label national de santé',
      logo: 'icones/all.jpg',
      seuil: 100,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.vitesse,
      unlocked: false,
    },
    {
      name: "Prix d'excellence hospitalière",
      logo: 'icones/all.jpg',
      seuil: 250,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  upgrades: [
    {
      name: 'Nouveau matériel de consultation',
      logo: 'icones/consultation.jpg',
      seuil: 1000,
      idcible: 1,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Scanner dernière génération',
      logo: 'icones/radiologie.jpg',
      seuil: 15000,
      idcible: 2,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Robot chirurgical',
      logo: 'icones/bloc.jpg',
      seuil: 100000,
      idcible: 3,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Automate de laboratoire',
      logo: 'icones/labo.jpg',
      seuil: 500000,
      idcible: 4,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Lits connectés',
      logo: 'icones/reanimation.jpg',
      seuil: 1200000,
      idcible: 5,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'IRM 3 Tesla',
      logo: 'icones/irm.jpg',
      seuil: 10000000,
      idcible: 6,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Formation continue du personnel',
      logo: 'icones/all.jpg',
      seuil: 50000,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.vitesse,
      unlocked: false,
    },
    {
      name: 'Logiciel de gestion des flux',
      logo: 'icones/all.jpg',
      seuil: 2000000,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.vitesse,
      unlocked: false,
    },
    {
      name: 'Partenariat pharmaceutique',
      logo: 'icones/all.jpg',
      seuil: 20000000,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Fondation caritative',
      logo: 'icones/all.jpg',
      seuil: 100000000,
      idcible: 0,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  angelupgrades: [
    {
      name: 'Don fondateur',
      logo: 'icones/mecene.jpg',
      seuil: 10,
      idcible: 0,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Réseau de mécènes',
      logo: 'icones/mecene.jpg',
      seuil: 100000,
      idcible: -1,
      ratio: 2,
      typeratio: RatioType.ange,
      unlocked: false,
    },
    {
      name: 'Fondation internationale',
      logo: 'icones/mecene.jpg',
      seuil: 100000000,
      idcible: -1,
      ratio: 2,
      typeratio: RatioType.ange,
      unlocked: false,
    },
    {
      name: 'Legs philanthropique',
      logo: 'icones/mecene.jpg',
      seuil: 1000000000,
      idcible: 0,
      ratio: 5,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  managers: [
    {
      name: 'Dr. Martin',
      logo: 'icones/dr_martin.jpg',
      seuil: 1000,
      idcible: 1,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Dubois',
      logo: 'icones/dr_dubois.jpg',
      seuil: 15000,
      idcible: 2,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Nguyen',
      logo: 'icones/dr_nguyen.jpg',
      seuil: 100000,
      idcible: 3,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Haddad',
      logo: 'icones/dr_haddad.jpg',
      seuil: 500000,
      idcible: 4,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Okafor',
      logo: 'icones/dr_okafor.jpg',
      seuil: 1200000,
      idcible: 5,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Lindqvist',
      logo: 'icones/dr_lindqvist.jpg',
      seuil: 10000000,
      idcible: 6,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
};